[package]
name = "net-route"
version = "0.1.4"
authors = ["Johnyburd <johnyburd8@gmail.com>"]

edition = "2021"
license = "MIT"
description = "This crate provides a cross-platform interface for manipulating the routing table"
homepage = "https://github.com/johnyburd/net-route"
repository = "https://github.com/johnyburd/net-route"
readme = "README.md"
keywords = ["route", "network", "ip"]

[package.metadata.docs.rs]

targets = ["x86_64-apple-darwin"]


[dependencies]
tokio = { version = "1", features = ["macros", "rt", "fs", "io-util"] }

[build-dependencies]
bindgen = "0.60.1"

